export enum ErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  SLOT_NOT_IN_AVAILABILITY = 'SLOT_NOT_IN_AVAILABILITY',
  SLOT_TAKEN = 'SLOT_TAKEN',
  SLOT_BLACKED_OUT = 'SLOT_BLACKED_OUT',
  AVAILABILITY_OVERLAP = 'AVAILABILITY_OVERLAP',
  AVAILABILITY_INVALID = 'AVAILABILITY_INVALID',
  VALIDATION = 'VALIDATION',
}

export abstract class DomainError extends Error {
  abstract readonly code: ErrorCode;
}
